---
sidebar: sidebar
api: true
explorer: false
permalink: 'get-application-consistency-groups-snapshots.html'
summary: 'Retrieve consistency group Snapshot copies'
---

= Retrieve consistency group Snapshot copies

[.api-doc-operation .api-doc-operation-get]#GET# [.api-doc-code-block]#`/application/consistency-groups/{consistency_group.uuid}/snapshots`#

*Introduced In:* 9.10

Retrieves Snapshot copies for a consistency group.

== Expensive properties

There is an added computational cost to retrieving values for these properties. They are not included by default in GET results and must be explicitly requested using the `fields` query parameter. See link:getting_started_with_the_ontap_rest_api.html#Requesting_specific_fields[DOC Requesting specific fields]  to learn more.

* `is_partial`
* `missing_voumes.uuid`
* `missing_voumes.name`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|consistency_group.uuid
|string
|path
|True
a|The unique identifier of the consistency group to retrieve.


|missing_volumes.uuid
|string
|query
|False
a|Filter by missing_volumes.uuid


|missing_volumes.name
|string
|query
|False
a|Filter by missing_volumes.name


|is_partial
|boolean
|query
|False
a|Filter by is_partial


|create_time
|string
|query
|False
a|Filter by create_time


|consistency_group.name
|string
|query
|False
a|Filter by consistency_group.name


|snapshot_volumes.snapshot.uuid
|string
|query
|False
a|Filter by snapshot_volumes.snapshot.uuid

* Introduced in: 9.12


|snapshot_volumes.snapshot.name
|string
|query
|False
a|Filter by snapshot_volumes.snapshot.name

* Introduced in: 9.12


|snapshot_volumes.volume.uuid
|string
|query
|False
a|Filter by snapshot_volumes.volume.uuid

* Introduced in: 9.12


|snapshot_volumes.volume.name
|string
|query
|False
a|Filter by snapshot_volumes.volume.name

* Introduced in: 9.12


|snapmirror_label
|string
|query
|False
a|Filter by snapmirror_label


|svm.name
|string
|query
|False
a|Filter by svm.name


|svm.uuid
|string
|query
|False
a|Filter by svm.uuid


|consistency_type
|string
|query
|False
a|Filter by consistency_type


|write_fence
|boolean
|query
|False
a|Filter by write_fence

* Introduced in: 9.14


|uuid
|string
|query
|False
a|Filter by uuid


|name
|string
|query
|False
a|Filter by name


|comment
|string
|query
|False
a|Filter by comment


|fields
|array[string]
|query
|False
a|Specify the fields to return.


|max_records
|integer
|query
|False
a|Limit the number of records returned.


|return_records
|boolean
|query
|False
a|The default is true for GET calls.  When set to false, only the number of records is returned.

* Default value: 1


|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

* Default value: 15
* Max value: 120
* Min value: 0


|order_by
|array[string]
|query
|False
a|Order results by specified fields and optional [asc|desc] direction. Default direction is 'asc' for ascending.

|===

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#collection_links[collection_links]
a|

|num_records
|integer
a|Number of records.


|records
|array[link:#records[records]]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "_links": {
    "next": {
      "href": "/api/resourcelink"
    },
    "self": {
      "href": "/api/resourcelink"
    }
  },
  "num_records": 1,
  "records": [
    {
      "_links": {
        "self": {
          "href": "/api/resourcelink"
        }
      },
      "comment": "My Snapshot copy comment",
      "consistency_group": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "my_consistency_group",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "consistency_type": "crash",
      "create_time": "2020-10-25 11:20:00 +0000",
      "is_partial": "",
      "missing_volumes": [
        {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "name": "volume1",
          "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
        }
      ],
      "name": "string",
      "snapmirror_label": "sm_label",
      "snapshot_volumes": [
        {
          "_links": {
            "self": {
              "href": "/api/resourcelink"
            }
          },
          "snapshot": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "this_snapshot",
            "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
          },
          "volume": {
            "_links": {
              "self": {
                "href": "/api/resourcelink"
              }
            },
            "name": "volume1",
            "uuid": "028baa66-41bd-11e9-81d5-00a0986138f7"
          }
        }
      ],
      "svm": {
        "_links": {
          "self": {
            "href": "/api/resourcelink"
          }
        },
        "name": "svm1",
        "uuid": "02c9e252-41be-11e9-81d5-00a0986138f7"
      },
      "uuid": "1cd8a442-86d1-11e0-ae1c-123478563412"
    }
  ]
}
====

== Error

```
Status: Default, Error
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|error
|link:#returned_error[returned_error]
a|

|===


.Example error
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "error": {
    "arguments": [
      {
        "code": "string",
        "message": "string"
      }
    ],
    "code": "4",
    "message": "entry doesn't exist",
    "target": "uuid"
  }
}
====

== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#collection_links]
[.api-collapsible-fifth-title]
collection_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|next
|link:#href[href]
a|

|self
|link:#href[href]
a|

|===


[#self_link]
[.api-collapsible-fifth-title]
self_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#consistency_group]
[.api-collapsible-fifth-title]
consistency_group

The consistency group of the Snapshot copy.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#self_link[self_link]
a|

|name
|string
a|The name of the consistency group.


|uuid
|string
a|The unique identifier of the consistency group.


|===


[#_links]
[.api-collapsible-fifth-title]
_links

[cols=3*,options=header]
|===
|Name
|Type
|Description

|self
|link:#href[href]
a|

|===


[#volume_reference]
[.api-collapsible-fifth-title]
volume_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the volume. This field cannot be specified in a POST or PATCH method.


|uuid
|string
a|Unique identifier for the volume. This corresponds to the instance-uuid that is exposed in the CLI and ONTAPI. It does not change due to a volume move.

* example: 028baa66-41bd-11e9-81d5-00a0986138f7
* Introduced in: 9.6
* x-nullable: true


|===


[#snapshot_reference]
[.api-collapsible-fifth-title]
snapshot_reference

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|

|uuid
|string
a|

|===


[#consistency_group_volume_snapshot]
[.api-collapsible-fifth-title]
consistency_group_volume_snapshot

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#self_link[self_link]
a|

|snapshot
|link:#snapshot_reference[snapshot_reference]
a|

|volume
|link:#volume_reference[volume_reference]
a|

|===


[#svm_reference]
[.api-collapsible-fifth-title]
svm_reference

SVM, applies only to SVM-scoped objects.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#_links[_links]
a|

|name
|string
a|The name of the SVM. This field cannot be specified in a PATCH method.


|uuid
|string
a|The unique identifier of the SVM. This field cannot be specified in a PATCH method.


|===


[#records]
[.api-collapsible-fifth-title]
records

[cols=3*,options=header]
|===
|Name
|Type
|Description

|_links
|link:#self_link[self_link]
a|

|comment
|string
a|Comment for the Snapshot copy.


|consistency_group
|link:#consistency_group[consistency_group]
a|The consistency group of the Snapshot copy.


|consistency_type
|string
a|Consistency type. This is for categorization purposes only. A Snapshot copy should not be set to 'application consistent' unless the host application is quiesced for the Snapshot copy. Valid in POST.


|create_time
|string
a|Time the snapshot copy was created


|is_partial
|boolean
a|Indicates whether the Snapshot copy taken is partial or not.


|missing_volumes
|array[link:#volume_reference[volume_reference]]
a|List of volumes which are not in the Snapshot copy.


|name
|string
a|Name of the Snapshot copy.


|snapmirror_label
|string
a|Snapmirror Label for the Snapshot copy.


|snapshot_volumes
|array[link:#consistency_group_volume_snapshot[consistency_group_volume_snapshot]]
a|List of volume and snapshot identifiers for each volume in the Snapshot copy.


|svm
|link:#svm_reference[svm_reference]
a|SVM, applies only to SVM-scoped objects.


|uuid
|string
a|The unique identifier of the Snapshot copy. The UUID is generated
by ONTAP when the Snapshot copy is created.

* example: 1cd8a442-86d1-11e0-ae1c-123478563412
* readOnly: 1
* Introduced in: 9.6
* x-nullable: true


|write_fence
|boolean
a|Specifies whether a write fence will be taken when creating the Snapshot copy. The default is false if there is only one volume in the consistency group, otherwise the default is true.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
