---
sidebar: sidebar
api: true
explorer: false
permalink: 'manage_keystores.html'
summary: 'Manage keystores'
---

= Manage keystores



== Overview

A keystore describes a key-manager configuration, specifically the type of key-manager and whether the configuration is currently enabled for the configured SVM.

== Examples

'''

=== Retrieving information for all configured key managers

The following example shows how to retrieve information about all configured key managers.

----

# The API:
GET /api/security/key-stores

# The call:
curl -X GET 'https://<mgmt-ip>/api/security/key-stores?fields=*' -H 'accept: application/hal+json'

# The response:
{
"records": [
  {
    "uuid": "33421d82-0a8d-11ec-ae88-005056bb5955",
    "configuration": {
      "name": "default",
      "uuid": "33421d82-0a8d-11ec-ae88-005056bb5955",
      "_links": {
        "self": {
          "href": "/api/security/azure-key-vaults/33421d82-0a8d-11ec-ae88-005056bb5955"
        }
      }
    },
    "enabled": true,
    "type": "akv",
    "location": "external",
    "_links": {
      "self": {
        "href": "/api/security/key-stores/33421d82-0a8d-11ec-ae88-005056bb5955"
      }
    }
  },
  {
    "uuid": "46a0b20a-0a8d-11ec-ae88-005056bb5955",
    "configuration": {
      "name": "default",
      "uuid": "46a0b20a-0a8d-11ec-ae88-005056bb5955",
      "_links": {
        "self": {
          "href": "/api/security/key-managers/46a0b20a-0a8d-11ec-ae88-005056bb5955"
        }
      }
    },
    "enabled": false,
    "type": "kmip",
    "location": "external",
    "_links": {
      "self": {
        "href": "/api/security/key-stores/46a0b20a-0a8d-11ec-ae88-005056bb5955"
      }
    }
  }
],
"num_records": 2,
"_links": {
  "self": {
    "href": "/api/security/key-stores?fields=*"
  }
}
}
----

'''

=== Retrieving a specific keystore by its UUID

The following example shows how to retrieve information about a specific keystore.

----

# The API:
GET /api/security/key-stores/{uuid}

# The call:
curl -X GET 'https://<mgmt-ip>/api/security/key-stores/33421d82-0a8d-11ec-ae88-005056bb5955?fields=*' -H 'accept: application/hal+json'

# The response:
{
"uuid": "33421d82-0a8d-11ec-ae88-005056bb5955",
"configuration": {
  "name": "default",
  "uuid": "33421d82-0a8d-11ec-ae88-005056bb5955",
  "_links": {
    "self": {
      "href": "/api/security/azure-key-vaults/33421d82-0a8d-11ec-ae88-005056bb5955"
    }
  }
},
"enabled": true,
"type": "akv",
"location": "external",
"_links": {
  "self": {
    "href": "/api/security/key-stores/33421d82-0a8d-11ec-ae88-005056bb5955?fields=*"
  }
}
}
----

'''

=== Enabling a specific keystore configuration

The following example shows how to enable a specific keystore configuration.

----

# The API:
PATCH /api/security/key-stores/{uuid}

# The call:
curl -X PATCH 'https://<mgmt-ip>/api/security/key-stores/33421d82-0a8d-11ec-ae88-005056bb5955' -H 'accept: application/hal+json' -d "{ \"enabled\": true }"
----

'''

=== Deleting a specific keystore configuration

The following example shows how to delete a specific keystore configuration. Only an inactive configuration can be deleted.

----

# The API:
DELETE /api/security/key-stores/{uuid}

# The call:
curl -X DELETE 'https://<mgmt-ip>/api/security/key-stores/33421d82-0a8d-11ec-ae88-005056bb5955' -H 'accept: application/hal+json'
----

'''


