---
sidebar: sidebar
api: true
explorer: false
permalink: 'patch-security.html'
summary: 'Update the software FIPS mode or enable conversion of non-encrypted metadata volumes non-NAE aggregates'
---

= Update the software FIPS mode or enable conversion of non-encrypted metadata volumes non-NAE aggregates

[.api-doc-operation .api-doc-operation-patch]#PATCH# [.api-doc-code-block]#`/security`#

*Introduced In:* 9.8

Updates the software FIPS mode or enables conversion of non-encrypted metadata volumes to encrypted metadata volumes and non-NAE aggregates to NAE aggregates.

== Related ONTAP commands

* `security config modify`


== Parameters

[cols=5*,options=header]
|===

|Name
|Type
|In
|Required
|Description

|return_timeout
|integer
|query
|False
a|The number of seconds to allow the call to execute before returning. When doing a POST, PATCH, or DELETE operation on a single record, the default is 0 seconds.  This means that if an asynchronous operation is started, the server immediately returns HTTP code 202 (Accepted) along with a link to the job.  If a non-zero value is specified for POST, PATCH, or DELETE operations, ONTAP waits that length of time to see if the job completes so it can return something other than 202.

* Default value: 0
* Max value: 120
* Min value: 0

|===

== Request Body

                

[cols=3*,options=header]
|===
|Name
|Type
|Description

|fips
|link:#fips[fips]
a|Cluster-wide Federal Information Processing Standards (FIPS) mode information.


|management_protocols
|link:#management_protocols[management_protocols]
a|Cluster-wide security protocols related information.


|software_data_encryption
|link:#software_data_encryption[software_data_encryption]
a|Cluster-wide software data encryption related information.


|tls
|link:#tls[tls]
a|Cluster-wide Transport Layer Security (TLS) configuration information


|===


.Example request
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "tls": {
    "cipher_suites": [
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    ],
    "protocol_versions": [
      "string"
    ]
  }
}
====

== Response

```
Status: 200, Ok
```


[cols=3*,options=header]
|===
|Name
|Type
|Description

|job
|link:#job_link[job_link]
a|

|===


.Example response
[%collapsible%closed]
====
[source,json,subs=+macros]
{
  "job": {
    "uuid": "string"
  }
}
====

== Response

```
Status: 202, Accepted
```

== Error

```
Status: Default
```

ONTAP Error Response Codes

|===
| Error Code | Description

| 5636142
| This operation is not supported in a mixed-release cluster.

| 5636145
| This operation is not supported when cluster security is configured with FIPS mode.

| 52428817
| SSLv3 is not supported when FIPS is enabled.

| 52428824
| TLSv1 is not supported when FIPS is enabled.

| 52428830
| Cannot enable FIPS-compliant mode because the configured minimum security strength for certificates is not compatible.

| 52428832
| TLSv1.1 is not supported when FIPS is enabled.

| 52559974
| Cannot enable FIPS-compliant mode because a certificate that is not FIPS-compliant is in use.

| 196608081
| Cannot start software encryption conversion while there are data volumes in the cluster.

| 196608082
| The operation is not valid when the MetroCluster is in switchover mode.
|===

Also see the table of common errors in the link:getting_started_with_the_ontap_rest_api.html#Response_body[Response body] overview section of this documentation.


== Definitions

[.api-def-first-level]
.See Definitions
[%collapsible%closed]
//Start collapsible Definitions block
====                
[#href]
[.api-collapsible-fifth-title]
href

[cols=3*,options=header]
|===
|Name
|Type
|Description

|href
|string
a|

|===


[#_links]
[.api-collapsible-fifth-title]
_links
[#fips]
[.api-collapsible-fifth-title]
fips

Cluster-wide Federal Information Processing Standards (FIPS) mode information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|enabled
|boolean
a|Indicates whether or not the software FIPS mode is enabled on the cluster. Our FIPS compliance involves configuring the use of only approved algorithms in applicable contexts (for example TLS), as well as the use of formally validated cryptographic module software implementations, where applicable. The US government documents concerning FIPS 140-2 outline the relevant security policies in detail.


|===


[#management_protocols]
[.api-collapsible-fifth-title]
management_protocols

Cluster-wide security protocols related information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|rsh_enabled
|boolean
a|Indicates whether or not security protocol rsh is enabled on the cluster.


|telnet_enabled
|boolean
a|Indicates whether or not security protocol telnet is enabled on the cluster.


|===


[#onboard_key_manager_configurable_status]
[.api-collapsible-fifth-title]
onboard_key_manager_configurable_status

Indicates whether the Onboard Key Manager can be configured in the cluster.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|integer
a|Code corresponding to the status message. Returns a 0 if the Onboard Key Manager can be configured in the cluster.


|message
|string
a|Reason that Onboard Key Manager cannot be configured in the cluster.


|supported
|boolean
a|Set to true if the Onboard Key Manager can be configured in the cluster.


|===


[#software_data_encryption]
[.api-collapsible-fifth-title]
software_data_encryption

Cluster-wide software data encryption related information.


[cols=3*,options=header]
|===
|Name
|Type
|Description

|conversion_enabled
|boolean
a|Indicates whether or not software encryption conversion is enabled on the cluster. A PATCH request initiates the conversion of all non-encrypted metadata volumes in the cluster to encrypted metadata volumes and all non-NAE aggregates to NAE aggregates. For the PATCH request to start, the cluster must have either an Onboard or an external key manager set up and the aggregates should either be empty or have only metadata volumes. No data volumes should be present in any of the aggregates in the cluster. For MetroCluster configurations, a PATCH request enables conversion on all the aggregates and metadata volumes of both local and remote clusters and is not allowed when the MetroCluster is in switchover state.


|disabled_by_default
|boolean
a|Indicates whether or not default software data at rest encryption is disabled on the cluster.


|===


[#tls]
[.api-collapsible-fifth-title]
tls

Cluster-wide Transport Layer Security (TLS) configuration information


[cols=3*,options=header]
|===
|Name
|Type
|Description

|cipher_suites
|array[string]
a|Names a cipher suite that the system can select during TLS handshakes. A list of available options can be found on the Internet Assigned Number Authority (IANA) website.


|protocol_versions
|array[string]
a|Names a TLS protocol version that the system can select during TLS handshakes. The use of SSLv3 or TLSv1 is discouraged.


|===


[#security_config]
[.api-collapsible-fifth-title]
security_config

[cols=3*,options=header]
|===
|Name
|Type
|Description

|fips
|link:#fips[fips]
a|Cluster-wide Federal Information Processing Standards (FIPS) mode information.


|management_protocols
|link:#management_protocols[management_protocols]
a|Cluster-wide security protocols related information.


|software_data_encryption
|link:#software_data_encryption[software_data_encryption]
a|Cluster-wide software data encryption related information.


|tls
|link:#tls[tls]
a|Cluster-wide Transport Layer Security (TLS) configuration information


|===


[#job_link]
[.api-collapsible-fifth-title]
job_link

[cols=3*,options=header]
|===
|Name
|Type
|Description

|uuid
|string
a|The UUID of the asynchronous job that is triggered by a POST, PATCH, or DELETE operation.


|===


[#error_arguments]
[.api-collapsible-fifth-title]
error_arguments

[cols=3*,options=header]
|===
|Name
|Type
|Description

|code
|string
a|Argument code


|message
|string
a|Message argument


|===


[#returned_error]
[.api-collapsible-fifth-title]
returned_error

[cols=3*,options=header]
|===
|Name
|Type
|Description

|arguments
|array[link:#error_arguments[error_arguments]]
a|Message arguments


|code
|string
a|Error code


|message
|string
a|Error message


|target
|string
a|The target parameter that caused the error.


|===


//end collapsible .Definitions block
====
